/** Location + league for Sideboard soccer-team nicknames (toasts / UI). */
export type TeamMeta = {
  location: string;
  league: string;
};

export const SOCCER_TEAM_META: Readonly<Record<string, TeamMeta>> = {
  'aalborg': { location: "Aalborg, Denmark", league: "Danish Superliga" },
  'aalesund': { location: "Ålesund, Norway", league: "Norwegian First Division" },
  'aarhus': { location: "Aarhus, Denmark", league: "Danish Superliga" },
  'aberdeen': { location: "Aberdeen, Scotland", league: "Scottish Premiership" },
  'ac-milan': { location: "Milan, Italy", league: "Serie A" },
  'ado-den-haag': { location: "The Hague, Netherlands", league: "Eerste Divisie" },
  'aik': { location: "Stockholm, Sweden", league: "Allsvenskan" },
  'ajaccio': { location: "Ajaccio, France", league: "Ligue 2" },
  'ajax': { location: "Amsterdam, Netherlands", league: "Eredivisie" },
  'al-ahly': { location: "Cairo, Egypt", league: "Egyptian Premier League" },
  'al-hilal': { location: "Riyadh, Saudi Arabia", league: "Saudi Pro League" },
  'alajuelense': { location: "Alajuela, Costa Rica", league: "Liga FPD" },
  'almere-city': { location: "Almere, Netherlands", league: "Eredivisie" },
  'amiens': { location: "Amiens, France", league: "Ligue 2" },
  'angers': { location: "Angers, France", league: "Ligue 1" },
  'anyang': { location: "Anyang, South Korea", league: "K League 1" },
  'argentinos-juniors': { location: "Buenos Aires, Argentina", league: "Argentine Primera División" },
  'arsenal': { location: "London, England", league: "Premier League" },
  'aston-villa': { location: "Birmingham, England", league: "Premier League" },
  'athletico-paranaense': { location: "Curitiba, Brazil", league: "Brasileirão Série A" },
  'atlanta-united': { location: "Atlanta, USA", league: "MLS" },
  'atlas': { location: "Guadalajara, Mexico", league: "Liga MX" },
  'atletico-madrid': { location: "Madrid, Spain", league: "La Liga" },
  'atletico-mineiro': { location: "Belo Horizonte, Brazil", league: "Brasileirão Série A" },
  'atletico-san-luis': { location: "San Luis Potosí, Mexico", league: "Liga MX" },
  'augsburg': { location: "Augsburg, Germany", league: "Bundesliga" },
  'austin-fc': { location: "Austin, USA", league: "MLS" },
  'auxerre': { location: "Auxerre, France", league: "Ligue 1" },
  'avispa-fukuoka': { location: "Fukuoka, Japan", league: "J1 League" },
  'az': { location: "Alkmaar, Netherlands", league: "Eredivisie" },
  'bahia': { location: "Salvador, Brazil", league: "Brasileirão Série A" },
  'banfield': { location: "Banfield, Argentina", league: "Argentine Primera División" },
  'barcelona': { location: "Barcelona, Spain", league: "La Liga" },
  'bayer-leverkusen': { location: "Leverkusen, Germany", league: "Bundesliga" },
  'bayern-munich': { location: "Munich, Germany", league: "Bundesliga" },
  'belgrano': { location: "Córdoba, Argentina", league: "Argentine Primera División" },
  'benfica': { location: "Lisbon, Portugal", league: "Primeira Liga" },
  'birmingham-legion': { location: "Birmingham, USA", league: "USL Championship" },
  'boca-juniors': { location: "Buenos Aires, Argentina", league: "Argentine Primera División" },
  'bodo-glimt': { location: "Bodø, Norway", league: "Eliteserien" },
  'bordeaux': { location: "Bordeaux, France", league: "Championnat National" },
  'borussia-dortmund': { location: "Dortmund, Germany", league: "Bundesliga" },
  'botafogo': { location: "Rio de Janeiro, Brazil", league: "Brasileirão Série A" },
  'bragantino': { location: "Bragança Paulista, Brazil", league: "Brasileirão Série A" },
  'brann': { location: "Bergen, Norway", league: "Eliteserien" },
  'brest': { location: "Brest, France", league: "Ligue 1" },
  'brommapojkarna': { location: "Stockholm, Sweden", league: "Allsvenskan" },
  'brondby': { location: "Brøndby, Denmark", league: "Danish Superliga" },
  'brooklyn-fc': { location: "Brooklyn, USA", league: "USL Championship" },
  'bucheon': { location: "Bucheon, South Korea", league: "K League 2" },
  'caen': { location: "Caen, France", league: "Ligue 2" },
  'cambuur': { location: "Leeuwarden, Netherlands", league: "Eerste Divisie" },
  'carmelita': { location: "Alajuela, Costa Rica", league: "Liga de Ascenso" },
  'cartagines': { location: "Cartago, Costa Rica", league: "Liga FPD" },
  'ceara': { location: "Fortaleza, Brazil", league: "Brasileirão Série A" },
  'celtic': { location: "Glasgow, Scotland", league: "Scottish Premiership" },
  'central-cordoba': { location: "Santiago del Estero, Argentina", league: "Argentine Primera División" },
  'cerezo-osaka': { location: "Osaka, Japan", league: "J1 League" },
  'cf-montreal': { location: "Montreal, Canada", league: "MLS" },
  'charleston-battery': { location: "Charleston, USA", league: "USL Championship" },
  'charlotte-fc': { location: "Charlotte, USA", league: "MLS" },
  'chelsea': { location: "London, England", league: "Premier League" },
  'chicago-fire': { location: "Chicago, USA", league: "MLS" },
  'chivas': { location: "Guadalajara, Mexico", league: "Liga MX" },
  'clermont': { location: "Clermont-Ferrand, France", league: "Ligue 2" },
  'club-america': { location: "Mexico City, Mexico", league: "Liga MX" },
  'cologne': { location: "Cologne, Germany", league: "Bundesliga" },
  'colorado-rapids': { location: "Commerce City, USA", league: "MLS" },
  'columbus-crew': { location: "Columbus, USA", league: "MLS" },
  'corinthians': { location: "São Paulo, Brazil", league: "Brasileirão Série A" },
  'cruz-azul': { location: "Mexico City, Mexico", league: "Liga MX" },
  'cruzeiro': { location: "Belo Horizonte, Brazil", league: "Brasileirão Série A" },
  'daejeon': { location: "Daejeon, South Korea", league: "K League 1" },
  'dc-united': { location: "Washington, D.C., USA", league: "MLS" },
  'defensa-y-justicia': { location: "Florencio Varela, Argentina", league: "Argentine Primera División" },
  'degerfors': { location: "Degerfors, Sweden", league: "Allsvenskan" },
  'detroit-city': { location: "Detroit, USA", league: "USL Championship" },
  'dijon': { location: "Dijon, France", league: "Championnat National" },
  'djurgarden': { location: "Stockholm, Sweden", league: "Allsvenskan" },
  'dundee': { location: "Dundee, Scotland", league: "Scottish Premiership" },
  'dundee-united': { location: "Dundee, Scotland", league: "Scottish Premiership" },
  'dynamo-kyiv': { location: "Kyiv, Ukraine", league: "Ukrainian Premier League" },
  'eintracht-frankfurt': { location: "Frankfurt, Germany", league: "Bundesliga" },
  'el-paso-locomotive': { location: "El Paso, USA", league: "USL Championship" },
  'elfsborg': { location: "Borås, Sweden", league: "Allsvenskan" },
  'emmen': { location: "Emmen, Netherlands", league: "Eerste Divisie" },
  'esbjerg': { location: "Esbjerg, Denmark", league: "Danish 1st Division" },
  'estudiantes': { location: "La Plata, Argentina", league: "Argentine Primera División" },
  'everton': { location: "Liverpool, England", league: "Premier League" },
  'excelsior': { location: "Rotterdam, Netherlands", league: "Eerste Divisie" },
  'fagiano-okayama': { location: "Okayama, Japan", league: "J1 League" },
  'falkirk': { location: "Falkirk, Scotland", league: "Scottish Championship" },
  'fc-cincinnati': { location: "Cincinnati, USA", league: "MLS" },
  'fc-copenhagen': { location: "Copenhagen, Denmark", league: "Danish Superliga" },
  'fc-dallas': { location: "Frisco, USA", league: "MLS" },
  'fc-seoul': { location: "Seoul, South Korea", league: "K League 1" },
  'fc-tokyo': { location: "Tokyo, Japan", league: "J1 League" },
  'fc-tulsa': { location: "Tulsa, USA", league: "USL Championship" },
  'feyenoord': { location: "Rotterdam, Netherlands", league: "Eredivisie" },
  'flamengo': { location: "Rio de Janeiro, Brazil", league: "Brasileirão Série A" },
  'fluminense': { location: "Rio de Janeiro, Brazil", league: "Brasileirão Série A" },
  'fortaleza': { location: "Fortaleza, Brazil", league: "Brasileirão Série A" },
  'fortuna-sittard': { location: "Sittard, Netherlands", league: "Eredivisie" },
  'fredrikstad': { location: "Fredrikstad, Norway", league: "Eliteserien" },
  'freiburg': { location: "Freiburg, Germany", league: "Bundesliga" },
  'gais': { location: "Gothenburg, Sweden", league: "Allsvenskan" },
  'galatasaray': { location: "Istanbul, Turkey", league: "Süper Lig" },
  'gamba-osaka': { location: "Osaka, Japan", league: "J1 League" },
  'gangwon': { location: "Gangneung, South Korea", league: "K League 1" },
  'gimcheon-sangmu': { location: "Gimcheon, South Korea", league: "K League 1" },
  'gimnasia': { location: "La Plata, Argentina", league: "Argentine Primera División" },
  'gladbach': { location: "Mönchengladbach, Germany", league: "Bundesliga" },
  'go-ahead-eagles': { location: "Deventer, Netherlands", league: "Eredivisie" },
  'godoy-cruz': { location: "Mendoza, Argentina", league: "Argentine Primera División" },
  'gremio': { location: "Porto Alegre, Brazil", league: "Brasileirão Série A" },
  'groningen': { location: "Groningen, Netherlands", league: "Eredivisie" },
  'guadalupe': { location: "Goicoechea, Costa Rica", league: "Liga de Ascenso" },
  'guanacasteca': { location: "Nicoya, Costa Rica", league: "Liga FPD" },
  'guingamp': { location: "Guingamp, France", league: "Ligue 2" },
  'gwangju': { location: "Gwangju, South Korea", league: "K League 1" },
  'hacken': { location: "Gothenburg, Sweden", league: "Allsvenskan" },
  'halmstad': { location: "Halmstad, Sweden", league: "Allsvenskan" },
  'hamburg': { location: "Hamburg, Germany", league: "2. Bundesliga" },
  'hammarby': { location: "Stockholm, Sweden", league: "Allsvenskan" },
  'hartford-athletic': { location: "Hartford, USA", league: "USL Championship" },
  'haugesund': { location: "Haugesund, Norway", league: "Eliteserien" },
  'hearts': { location: "Edinburgh, Scotland", league: "Scottish Premiership" },
  'heerenveen': { location: "Heerenveen, Netherlands", league: "Eredivisie" },
  'heidenheim': { location: "Heidenheim, Germany", league: "Bundesliga" },
  'helsingborg': { location: "Helsingborg, Sweden", league: "Superettan" },
  'heracles': { location: "Almelo, Netherlands", league: "Eredivisie" },
  'herediano': { location: "Heredia, Costa Rica", league: "Liga FPD" },
  'hibernian': { location: "Edinburgh, Scotland", league: "Scottish Premiership" },
  'hoffenheim': { location: "Sinsheim, Germany", league: "Bundesliga" },
  'horsens': { location: "Horsens, Denmark", league: "Danish 1st Division" },
  'houston-dynamo': { location: "Houston, USA", league: "MLS" },
  'huracan': { location: "Buenos Aires, Argentina", league: "Argentine Primera División" },
  'ifk-goteborg': { location: "Gothenburg, Sweden", league: "Allsvenskan" },
  'norrkoping': { location: "Norrköping, Sweden", league: "Allsvenskan" },
  'incheon-united': { location: "Incheon, South Korea", league: "K League 1" },
  'independiente': { location: "Avellaneda, Argentina", league: "Argentine Primera División" },
  'indy-eleven': { location: "Indianapolis, USA", league: "USL Championship" },
  'instituto': { location: "Córdoba, Argentina", league: "Argentine Primera División" },
  'inter-miami': { location: "Fort Lauderdale, USA", league: "MLS" },
  'inter-milan': { location: "Milan, Italy", league: "Serie A" },
  'internacional': { location: "Porto Alegre, Brazil", league: "Brasileirão Série A" },
  'jef-united': { location: "Chiba, Japan", league: "J2 League" },
  'jeju-sk': { location: "Jeju, South Korea", league: "K League 1" },
  'jeonbuk': { location: "Jeonju, South Korea", league: "K League 1" },
  'juarez': { location: "Ciudad Juárez, Mexico", league: "Liga MX" },
  'juventude': { location: "Caxias do Sul, Brazil", league: "Brasileirão Série A" },
  'juventus': { location: "Turin, Italy", league: "Serie A" },
  'kalmar': { location: "Kalmar, Sweden", league: "Superettan" },
  'kashima-antlers': { location: "Kashima, Japan", league: "J1 League" },
  'kashiwa-reysol': { location: "Kashiwa, Japan", league: "J1 League" },
  'kawasaki-frontale': { location: "Kawasaki, Japan", league: "J1 League" },
  'kfum-oslo': { location: "Oslo, Norway", league: "Eliteserien" },
  'kilmarnock': { location: "Kilmarnock, Scotland", league: "Scottish Premiership" },
  'kristiansund': { location: "Kristiansund, Norway", league: "Eliteserien" },
  'kyoto-sanga': { location: "Kyoto, Japan", league: "J1 League" },
  'la-galaxy': { location: "Carson, USA", league: "MLS" },
  'lafc': { location: "Los Angeles, USA", league: "MLS" },
  'lanus': { location: "Lanús, Argentina", league: "Argentine Primera División" },
  'las-vegas-lights': { location: "Las Vegas, USA", league: "USL Championship" },
  'lazio': { location: "Rome, Italy", league: "Serie A" },
  'le-havre': { location: "Le Havre, France", league: "Ligue 1" },
  'le-mans': { location: "Le Mans, France", league: "Ligue 2" },
  'leeds-united': { location: "Leeds, England", league: "Premier League" },
  'leicester-city': { location: "Leicester, England", league: "Championship" },
  'lens': { location: "Lens, France", league: "Ligue 1" },
  'leon': { location: "León, Mexico", league: "Liga MX" },
  'lexington-sc': { location: "Lexington, USA", league: "USL Championship" },
  'liberia': { location: "Liberia, Costa Rica", league: "Liga FPD" },
  'lille': { location: "Lille, France", league: "Ligue 1" },
  'lillestrom': { location: "Lillestrøm, Norway", league: "Eliteserien" },
  'limon': { location: "Limón, Costa Rica", league: "Liga de Ascenso" },
  'liverpool': { location: "Liverpool, England", league: "Premier League" },
  'livingston': { location: "Livingston, Scotland", league: "Scottish Championship" },
  'lorient': { location: "Lorient, France", league: "Ligue 1" },
  'loudoun-united': { location: "Leesburg, USA", league: "USL Championship" },
  'louisville-city': { location: "Louisville, USA", league: "USL Championship" },
  'lyngby': { location: "Kongens Lyngby, Denmark", league: "Danish Superliga" },
  'lyon': { location: "Lyon, France", league: "Ligue 1" },
  'machida-zelvia': { location: "Machida, Japan", league: "J1 League" },
  'mainz': { location: "Mainz, Germany", league: "Bundesliga" },
  'malmo': { location: "Malmö, Sweden", league: "Allsvenskan" },
  'manchester-city': { location: "Manchester, England", league: "Premier League" },
  'manchester-united': { location: "Manchester, England", league: "Premier League" },
  'marseille': { location: "Marseille, France", league: "Ligue 1" },
  'mazatlan': { location: "Mazatlán, Mexico", league: "Liga MX" },
  'metz': { location: "Metz, France", league: "Ligue 1" },
  'miami-fc': { location: "Miami, USA", league: "USL Championship" },
  'midtjylland': { location: "Herning, Denmark", league: "Danish Superliga" },
  'minnesota-united': { location: "Saint Paul, USA", league: "MLS" },
  'mirassol': { location: "Mirassol, Brazil", league: "Brasileirão Série A" },
  'mito-hollyhock': { location: "Mito, Japan", league: "J2 League" },
  'mjallby': { location: "Hällevik, Sweden", league: "Allsvenskan" },
  'molde': { location: "Molde, Norway", league: "Eliteserien" },
  'monaco': { location: "Monaco", league: "Ligue 1" },
  'monterey-bay': { location: "Monterey, USA", league: "USL Championship" },
  'monterrey': { location: "Monterrey, Mexico", league: "Liga MX" },
  'montpellier': { location: "Montpellier, France", league: "Ligue 2" },
  'motherwell': { location: "Motherwell, Scotland", league: "Scottish Premiership" },
  'grecia': { location: "Grecia, Costa Rica", league: "Liga de Ascenso" },
  'nac-breda': { location: "Breda, Netherlands", league: "Eredivisie" },
  'nagoya-grampus': { location: "Nagoya, Japan", league: "J1 League" },
  'nancy': { location: "Nancy, France", league: "Ligue 2" },
  'nantes': { location: "Nantes, France", league: "Ligue 1" },
  'napoli': { location: "Naples, Italy", league: "Serie A" },
  'nashville-sc': { location: "Nashville, USA", league: "MLS" },
  'nec': { location: "Nijmegen, Netherlands", league: "Eredivisie" },
  'necaxa': { location: "Aguascalientes, Mexico", league: "Liga MX" },
  'new-england': { location: "Foxborough, USA", league: "MLS" },
  'new-mexico-united': { location: "Albuquerque, USA", league: "USL Championship" },
  'newcastle': { location: "Newcastle, England", league: "Premier League" },
  'newells': { location: "Rosario, Argentina", league: "Argentine Primera División" },
  'nice': { location: "Nice, France", league: "Ligue 1" },
  'nimes': { location: "Nîmes, France", league: "Championnat National" },
  'nordsjaelland': { location: "Farum, Denmark", league: "Danish Superliga" },
  'ny-red-bulls': { location: "Harrison, USA", league: "MLS" },
  'nycfc': { location: "New York City, USA", league: "MLS" },
  'oakland-roots': { location: "Oakland, USA", league: "USL Championship" },
  'ob-odense': { location: "Odense, Denmark", league: "Danish Superliga" },
  'odd': { location: "Skien, Norway", league: "Norwegian First Division" },
  'olympiacos': { location: "Piraeus, Greece", league: "Super League Greece" },
  'orange-county-sc': { location: "Irvine, USA", league: "USL Championship" },
  'orebro': { location: "Örebro, Sweden", league: "Superettan" },
  'orlando-city': { location: "Orlando, USA", league: "MLS" },
  'pachuca': { location: "Pachuca, Mexico", league: "Liga MX" },
  'palmeiras': { location: "São Paulo, Brazil", league: "Brasileirão Série A" },
  'paris-fc': { location: "Paris, France", league: "Ligue 1" },
  'psg': { location: "Paris, France", league: "Ligue 1" },
  'pec-zwolle': { location: "Zwolle, Netherlands", league: "Eredivisie" },
  'perez-zeledon': { location: "San Isidro, Costa Rica", league: "Liga FPD" },
  'philadelphia-union': { location: "Chester, USA", league: "MLS" },
  'phoenix-rising': { location: "Phoenix, USA", league: "USL Championship" },
  'pittsburgh-riverhounds': { location: "Pittsburgh, USA", league: "USL Championship" },
  'platense': { location: "Florida, Argentina", league: "Argentine Primera División" },
  'pohang-steelers': { location: "Pohang, South Korea", league: "K League 1" },
  'portland-timbers': { location: "Portland, USA", league: "MLS" },
  'porto': { location: "Porto, Portugal", league: "Primeira Liga" },
  'psv': { location: "Eindhoven, Netherlands", league: "Eredivisie" },
  'puebla': { location: "Puebla, Mexico", league: "Liga MX" },
  'pumas': { location: "Mexico City, Mexico", league: "Liga MX" },
  'puntarenas': { location: "Puntarenas, Costa Rica", league: "Liga FPD" },
  'queretaro': { location: "Querétaro, Mexico", league: "Liga MX" },
  'racing': { location: "Avellaneda, Argentina", league: "Argentine Primera División" },
  'randers': { location: "Randers, Denmark", league: "Danish Superliga" },
  'rangers': { location: "Glasgow, Scotland", league: "Scottish Premiership" },
  'rb-leipzig': { location: "Leipzig, Germany", league: "Bundesliga" },
  'real-madrid': { location: "Madrid, Spain", league: "La Liga" },
  'real-salt-lake': { location: "Sandy, USA", league: "MLS" },
  'red-star': { location: "Saint-Ouen, France", league: "Ligue 2" },
  'reims': { location: "Reims, France", league: "Ligue 2" },
  'rennes': { location: "Rennes, France", league: "Ligue 1" },
  'rhode-island-fc': { location: "Pawtucket, USA", league: "USL Championship" },
  'river-plate': { location: "Buenos Aires, Argentina", league: "Argentine Primera División" },
  'rkc': { location: "Waalwijk, Netherlands", league: "Eredivisie" },
  'roma': { location: "Rome, Italy", league: "Serie A" },
  'rosario-central': { location: "Rosario, Argentina", league: "Argentine Primera División" },
  'rosenborg': { location: "Trondheim, Norway", league: "Eliteserien" },
  'sacramento-republic': { location: "Sacramento, USA", league: "USL Championship" },
  'saint-etienne': { location: "Saint-Étienne, France", league: "Ligue 2" },
  'san-antonio-fc': { location: "San Antonio, USA", league: "USL Championship" },
  'san-carlos': { location: "Quesada, Costa Rica", league: "Liga FPD" },
  'san-diego-fc': { location: "San Diego, USA", league: "MLS" },
  'san-jose-earthquakes': { location: "San Jose, USA", league: "MLS" },
  'san-lorenzo': { location: "Buenos Aires, Argentina", league: "Argentine Primera División" },
  'sanfrecce-hiroshima': { location: "Hiroshima, Japan", league: "J1 League" },
  'santos': { location: "Santos, Brazil", league: "Brasileirão Série A" },
  'santos-guapiles': { location: "Guápiles, Costa Rica", league: "Liga FPD" },
  'santos-laguna': { location: "Torreón, Mexico", league: "Liga MX" },
  'sao-paulo': { location: "São Paulo, Brazil", league: "Brasileirão Série A" },
  'saprissa': { location: "San José, Costa Rica", league: "Liga FPD" },
  'sarpsborg': { location: "Sarpsborg, Norway", league: "Eliteserien" },
  'schalke': { location: "Gelsenkirchen, Germany", league: "2. Bundesliga" },
  'seattle-sounders': { location: "Seattle, USA", league: "MLS" },
  'sevilla': { location: "Seville, Spain", league: "La Liga" },
  'shakhtar': { location: "Donetsk, Ukraine", league: "Ukrainian Premier League" },
  'shimizu-s-pulse': { location: "Shizuoka, Japan", league: "J1 League" },
  'silkeborg': { location: "Silkeborg, Denmark", league: "Danish Superliga" },
  'sirius': { location: "Uppsala, Sweden", league: "Allsvenskan" },
  'sochaux': { location: "Montbéliard, France", league: "Championnat National" },
  'sonderjyske': { location: "Haderslev, Denmark", league: "Danish Superliga" },
  'sparta-rotterdam': { location: "Rotterdam, Netherlands", league: "Eredivisie" },
  'sport-recife': { location: "Recife, Brazil", league: "Brasileirão Série A" },
  'sporting': { location: "Lisbon, Portugal", league: "Primeira Liga" },
  'sporting-jax': { location: "Jacksonville, USA", league: "MLS Next Pro" },
  'sporting-kc': { location: "Kansas City, USA", league: "MLS" },
  'sporting-san-jose': { location: "San José, Costa Rica", league: "Liga FPD" },
  'st-mirren': { location: "Paisley, Scotland", league: "Scottish Premiership" },
  'st-louis-city': { location: "St. Louis, USA", league: "MLS" },
  'st-pauli': { location: "Hamburg, Germany", league: "Bundesliga" },
  'stabaek': { location: "Bærum, Norway", league: "Norwegian First Division" },
  'strasbourg': { location: "Strasbourg, France", league: "Ligue 1" },
  'stromsgodset': { location: "Drammen, Norway", league: "Eliteserien" },
  'stuttgart': { location: "Stuttgart, Germany", league: "Bundesliga" },
  'switchbacks': { location: "Colorado Springs, USA", league: "USL Championship" },
  'talleres': { location: "Córdoba, Argentina", league: "Argentine Primera División" },
  'tampa-bay-rowdies': { location: "St. Petersburg, USA", league: "USL Championship" },
  'tigre': { location: "Victoria, Argentina", league: "Argentine Primera División" },
  'tigres': { location: "San Nicolás de los Garza, Mexico", league: "Liga MX" },
  'tijuana': { location: "Tijuana, Mexico", league: "Liga MX" },
  'tokyo-verdy': { location: "Tokyo, Japan", league: "J1 League" },
  'toluca': { location: "Toluca, Mexico", league: "Liga MX" },
  'toronto-fc': { location: "Toronto, Canada", league: "MLS" },
  'tottenham': { location: "London, England", league: "Premier League" },
  'toulouse': { location: "Toulouse, France", league: "Ligue 1" },
  'tromso': { location: "Tromsø, Norway", league: "Eliteserien" },
  'troyes': { location: "Troyes, France", league: "Ligue 2" },
  'twente': { location: "Enschede, Netherlands", league: "Eredivisie" },
  'ulsan-hd': { location: "Ulsan, South Korea", league: "K League 1" },
  'union': { location: "Santa Fe, Argentina", league: "Argentine Primera División" },
  'union-berlin': { location: "Berlin, Germany", league: "Bundesliga" },
  'urawa-reds': { location: "Saitama, Japan", league: "J1 League" },
  'utrecht': { location: "Utrecht, Netherlands", league: "Eredivisie" },
  'v-varen-nagasaki': { location: "Nagasaki, Japan", league: "J2 League" },
  'valencia': { location: "Valencia, Spain", league: "La Liga" },
  'valerenga': { location: "Oslo, Norway", league: "Eliteserien" },
  'vancouver-whitecaps': { location: "Vancouver, Canada", league: "MLS" },
  'varnamo': { location: "Värnamo, Sweden", league: "Allsvenskan" },
  'vasco': { location: "Rio de Janeiro, Brazil", league: "Brasileirão Série A" },
  'vejle': { location: "Vejle, Denmark", league: "Danish Superliga" },
  'velez': { location: "Buenos Aires, Argentina", league: "Argentine Primera División" },
  'viborg': { location: "Viborg, Denmark", league: "Danish Superliga" },
  'viking': { location: "Stavanger, Norway", league: "Eliteserien" },
  'vissel-kobe': { location: "Kobe, Japan", league: "J1 League" },
  'vitesse': { location: "Arnhem, Netherlands", league: "Eerste Divisie" },
  'vitoria': { location: "Salvador, Brazil", league: "Brasileirão Série A" },
  'volendam': { location: "Volendam, Netherlands", league: "Eredivisie" },
  'werder-bremen': { location: "Bremen, Germany", league: "Bundesliga" },
  'west-ham': { location: "London, England", league: "Premier League" },
  'willem-ii': { location: "Tilburg, Netherlands", league: "Eerste Divisie" },
  'wolfsburg': { location: "Wolfsburg, Germany", league: "Bundesliga" },
  'yokohama-marinos': { location: "Yokohama, Japan", league: "J1 League" },
};
