import { StyleSheet } from 'react-native';

export const palette = {
  bg: '#121212',
  elevated: '#18191a',
  hover: '#242424',
  border: '#2e2e32',
  text: '#ededed',
  secondary: '#c6c6c6',
  muted: '#9b9b9b',
  accent: '#007fd4',
  accentDim: '#0e639c',
  ok: '#4ade80',
  warn: '#cca700',
  err: '#f87171',
};


export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.bg },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 16 },
  brandName: { color: palette.text, fontSize: 15, fontWeight: '600', letterSpacing: -0.3 },
  chromeMark: { marginRight: 2 },
  header: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 12 },
  title: { color: palette.text, fontSize: 22, fontWeight: '600', letterSpacing: -0.3, marginBottom: 8 },
  emptyFill: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 28, paddingBottom: 24 },
  empty: { alignItems: 'center' },
  emptyMark: { width: 52, height: 52, marginBottom: 18 },
  emptyPlate: {
    position: 'absolute',
    left: 8,
    top: 8,
    width: 36,
    height: 36,
    borderRadius: 6,
    backgroundColor: 'rgba(0, 127, 212, 0.25)',
    transform: [{ rotate: '14deg' }, { translateX: 6 }, { translateY: 6 }],
  },
  emptyCube: {
    position: 'absolute',
    left: 8,
    top: 8,
    width: 36,
    height: 36,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: palette.text,
    opacity: 0.55,
    transform: [{ rotate: '14deg' }],
  },
  emptyTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: -0.3,
    textAlign: 'center',
    marginBottom: 8,
  },
  emptyBody: { color: palette.muted, fontSize: 14, lineHeight: 21, textAlign: 'center' },
  hint: { color: palette.muted, fontSize: 14, lineHeight: 20 },
  chrome: {
    minHeight: 44,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  chromeTitle: { flex: 1, color: palette.text, fontSize: 15, fontWeight: '600', letterSpacing: -0.2 },
  link: { color: palette.accent, fontSize: 14, fontWeight: '600' },
  form: { paddingHorizontal: 16, gap: 8 },
  label: { color: palette.muted, fontSize: 12, marginTop: 4 },
  input: {
    backgroundColor: palette.bg,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 6,
    color: palette.text,
    fontSize: 15,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  codeInput: { letterSpacing: 2, fontSize: 18 },
  error: { color: palette.err, fontSize: 14, marginTop: 4 },
  errorPad: { paddingHorizontal: 16, marginBottom: 4 },
  primary: {
    marginTop: 8,
    backgroundColor: palette.accentDim,
    borderWidth: 1,
    borderColor: palette.accent,
    borderRadius: 6,
    paddingVertical: 12,
    alignItems: 'center',
  },
  primaryDisabled: { opacity: 0.45 },
  primaryText: { color: palette.text, fontSize: 15, fontWeight: '600' },
  footer: { padding: 16, borderTopWidth: 1, borderTopColor: palette.border },
  transcript: { flex: 1 },
  listPad: { padding: 16, paddingBottom: 24 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.elevated,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    gap: 8,
  },
  rowMain: { flex: 1 },
  rowTitle: { color: palette.text, fontSize: 16, fontWeight: '600' },
  titleFlex: { flex: 1 },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, minWidth: 0 },
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4 },
  status: { color: palette.muted, fontSize: 13 },
  dot: { width: 7, height: 7, borderRadius: 4 },
  dotOn: { backgroundColor: palette.ok },
  dotOff: { backgroundColor: palette.muted },
  dotWarn: { backgroundColor: palette.warn },
  dotRun: { backgroundColor: palette.accent },
  dotErr: { backgroundColor: palette.err },
  preview: { color: palette.muted, fontSize: 13, lineHeight: 18, marginTop: 4 },
  projectName: { flex: 1, color: palette.text, fontSize: 16, fontWeight: '600' },
  worktreeName: { flex: 1, color: palette.secondary, fontSize: 13 },
  glyphRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8, minWidth: 0 },
  projectBlock: { marginTop: 12 },
  worktreeBlock: { marginLeft: 8, marginBottom: 4 },
  meta: { color: palette.muted, fontSize: 13, marginBottom: 8 },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    gap: 8,
  },
  sectionLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  projectsHead: { marginTop: 16 },
  historyLead: { marginBottom: 12 },
  historyForm: { paddingTop: 12 },
  historyButton: { alignItems: 'center', paddingVertical: 4 },
  addAgent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 32,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: palette.hover,
  },
  addAgentPlus: { color: palette.text, fontSize: 16, fontWeight: '600', marginTop: -1 },
  addAgentText: { color: palette.text, fontSize: 13, fontWeight: '600' },
  ghost: {
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  ghostText: { color: palette.muted, fontSize: 13, fontWeight: '600' },
  bubble: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 8,
  },
  user: {
    alignSelf: 'stretch',
    backgroundColor: palette.elevated,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.border,
  },
  agent: {
    alignSelf: 'stretch',
    backgroundColor: 'transparent',
  },
  streamRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 2,
    marginBottom: 8,
    minHeight: 22,
  },
  streamVerb: { flex: 1, fontSize: 16, lineHeight: 22, letterSpacing: -0.2 },
  streamDots: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  streamDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: palette.muted },
  ask: { marginTop: 8, marginBottom: 12, gap: 6 },
  askText: { color: palette.text, fontSize: 16, fontWeight: '500', lineHeight: 22, marginBottom: 4 },
  option: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  optionNum: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  optionNumText: { color: palette.muted, fontSize: 11 },
  optionBody: { flex: 1, gap: 2 },
  optionLabel: { color: palette.text, fontSize: 15, fontWeight: '500' },
  optionDesc: { color: palette.muted, fontSize: 13, lineHeight: 18 },
  composerShell: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    backgroundColor: palette.bg,
  },
  composerBox: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 14,
    backgroundColor: palette.elevated,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 8,
    gap: 8,
  },
  composerInput: {
    color: palette.text,
    fontSize: 16,
    lineHeight: 22,
    minHeight: 44,
    maxHeight: 140,
    padding: 0,
  },
  composerActions: { flexDirection: 'row', justifyContent: 'flex-end' },
  send: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: palette.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendDisabled: { opacity: 0.35 },
  sendText: { color: palette.bg, fontSize: 16, fontWeight: '700', marginTop: -1 },
});

